version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_dev
    command: npm start
    container_name: angular-template-dev
    image: angular-template/dev
    volumes:
      - ./src:/home/node/angular-template/src
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
